FROM bellsoft/liberica-openjdk-centos:17

WORKDIR /app

RUN sed -e 's|^mirrorlist=|#mirrorlist=|g' \
    -e 's|^#baseurl=http://mirror.centos.org/centos|baseurl=https://mirrors.tuna.tsinghua.edu.cn/centos|g' \
    -i.bak \
    /etc/yum.repos.d/CentOS-*.repo

RUN yum update -y && \
    yum install -y \
        maven \
        && \
    yum clean all \
    && \
    rm -rf /var/cache/yum

ADD ./ .

RUN mvn -version

RUN mvn dependency:resolve

RUN mvn package -DskipTests

FROM bellsoft/liberica-openjdk-centos:17

WORKDIR /app

COPY --from=0 /app/target/shop_online-0.0.1-SNAPSHOT.jar ./shop_online.jar

ENTRYPOINT ["java", "-jar", "/app/shop_online.jar"]

EXPOSE 8088